# Generated by Django 5.1.4 on 2025-01-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
