# Generated by Django 5.1.4 on 2025-01-07 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_password_reset_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
